simulate the error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,5 +9,9 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Run a one-line script
+      - name: Greeting
+        run: echo "Hello, world!"
+      - name: Simulating an error
+        run: echo "About to fail" ; exit 1
+      - name: Another Greeting
         run: echo "Hello, world!"
